language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial   
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

addons:
  artifacts:
    paths:
      - $(ls ./dist/* | tr "\n" ":")
    s3_region: "us-east-2"

env:
 global:
  - secure: "JpWaszi9FVvUbWg2fI1xDPgjEM3g8znLQJctwYxgVaBvySHRAlISw2x1DtHXqVdQ1oTpCLGJpO24yB+F5ktLNfKqf7Ic527Tt2NBQo83gkrgaiM0mN66kdZCMRBhC8im+AOD8ygNDrPa1fLnb7I5jV+JZSSeHBXuUXdLZh7aAjc+gDF/2sCL3RXLGzVLO2eyjdAHM3Kl4DMgOA2DXfrYZmjouEaCdhCofoFsbvHFKVClAzKeZ7yPB1tIUZVyPNbUXUr9+W+KT4C5iEQXu7ycpOLW4hgPwZAvLQUYKIsQRZH3SYMsWRlWY3hY/uLWPiiejKKCV+BJs/wK+BmDEXbcRU1HY5x7zej5VfiV5I+S2RHBu7NEg1+AsZS2JX3lGGt3KUshOhiFXuctQdrfP8acVwKD+bpEBi6eF0yuPGIqTE8zcuW4WMXulQmyOKxoutNeR8v0u+/SW8koIJ5bcNZ9zaGwtxJdh3tz/ys+/RVSkt2yujq5CN0HdH7ES4y4tin1Jk7fQLqUG6uqZD6XNr8P6SBbhYYOzoPVuT/Z7LWluaZ179iVLpoJDBxIXJyPQmh3z2GA6/qmIwmw041yuH5zjYdsuGP13vf3YuLcbd0/a5whlpEbuZfvu862d4pAsjCywzba7QAtE6WJz1H9C3WeKASWN3i1Ntbgirb4Zd2IILA="
  - secure: "SPrHa2ryy8fRuq14Mm5BkAv0McguDgHqD3jOStrYVjH0xDgsJ2L37XXhkS1f1SDbYJRovqQFQj1utr1OHHbZYq29mJtDhQmJDUk0rm5yXq71Q/ob88KIrq13NSWzdZj3f9mU5jltEU7RYjFZGrn9yFD/1RtVbpXYjQaJ4EPiki2iMR6LqI/0aHvUiFQyhs6ZLskVO2a67DDwAA7VkAKjhxxKCUvhYFpTo/i+eLHEf5O5X1q03v4by03pAVuAptDz1JMe94Vaw49naq5rT/7Eny0+LtS9TPyUNUdDP5dsQBgKud4NZX4tGnSDnDr0KbLfix9ucrh2O9p4S5cWwZ26+UPiGkurMdxesa3GQVHOVMK394y1/WNV/DqZErJSMtLLnI/UIB8uF4clpXtGdzgbKIIup8C0ltg3k/CnjUHAUjsF4X4OyzxbZf/q4knNNK1OE1MovsoKWDb/OPlvFHi+YxQU5Cgb1Tlgs69dPihz96Pz7mnwpNcfZ1QucdrMpPWTj+ViQf5GLd9OAtme8ahF4IKHm3DK5Fp90aRXMXrzDUhlDMPbBa+kLo8w7llHshIf0FOjeUUuPpqpUeubsguv2l+hjqGBphV75NAwGxGEUzS8G84btHGx2wc/w7Vh5OZzV9YJWl3j9c4G0GWbsK8GPd0dtle61YFnV0TG2cUzzNo="
  - secure: "OwZrnXZ7mrQJEqJ4QcUyAgpjfgdo3YcI+l5K1c0x0UrfW3M7Or0QQDBx2pHw8bwBt+LMtu9SFEmbEShq1sOpL+5RIYZf9qY/xhQ0n3I4WNryCf7jJDbvXpGodULec+QRUd22O1P6xRl98V/Pam0O4SOCz7XDZG9EAakP9QYL7Qiop5zFfqEQdkykOlaofosqQPwAYSxKPeClGwONJLGUZdhNEzNERbglDBxefESuAGajATE9gLH6c9vJwc50Vu1Cn6nCP9l5rl/TOqNEaSp3gVmAHeg+L0oGLHXpHXlXbDQColcpc8OP11rt7EPVADwOPke1ikp89Yt46hzP71XKWjk8Doa4mLD6N8NkSC/XXYL130QxERhNMa68HRCJKGFUZWdt3oCuQ4D8cM3f+t+zK++jtNOpnnf7As7YJZv1PJhEPox6aBe17YhjMD2DogdPfkb/wa4QLd0YmV+mZ1W6IMaprzEIBESiwEk9kuoYWiiWv4l1FgWNH1xJFCOisxySg3UIXaWoyExf6MkiUSA14K/E2kdWZNJbweDR2l8LX1xIFcdRkNBaiFGr7+NX/E9OKPmNFMG3h3EyJgZWFuQAQWa1YhOngFRH1a4CnG0nLBq9vcY8yqNJo+lowyXL0bxGNUFLLiYXW2XoXH9kNnPOrYZmIFT2QWtqBUThYjTqXeQ="

install:
  - pip3 install --upgrade pip
  - pip3 install -r dev-requirements.txt
  - python3 --version

script:
  - if [ -z $TRAVIS_TAG ]; then export NEW_NAME="pyinstallertest-build${TRAVIS_BUILD_NUMBER}_${TRAVIS_OS_NAME}"; else export NEW_NAME="pyinstallertest-${TRAVIS_TAG}_${TRAVIS_OS_NAME}"; fi
  - pyinstaller -F ./main.py -n "$NEW_NAME"
  
before_deploy:
  - export FILE_TO_UPLOAD=$(ls dist/*)

deploy:
  provider: releases
  api_key:
    - secure: "hJaO3097yKJPRF4+7D45PPmo9nLXncp/MTCA5/+sRlQ1vC2LY4f84AsIU85fh2v1M2awvbnL5VEWfohIRarF2XrD5P8ge8om0F0rPLc8R+vCOFzOQccutxAbk4xFAJS+2OIjOgPwzJqxa8dVG74RsSskWjruDykYTMXJJO5XSva6UUoEaZtKy1nJJABJtgwFvlbaEHOyrbvOAVs7MOcZJ6keRfKSa02jxwt+mWZion3fNQIuUZJOJO77k84ruTWgf9uHxiSxHX/MxWe+KQc/A8IV7HApq4cNpq3Z50GRMuNCzdM1CRURZq3nGnb1RkGX0Mw7cqJbo0YaRksGp0pG4EH2uVWyBBUtuoUoWVK9UnWHA++s1soMOd6tAXF4Da95UsNAfj3X7hrvUR5wDT1SlMxL88o/KpW5GJyiP9+U6Tpanh+bmASOo1eDfhl8aQajmI7RUEoe+QS1a3Kw9VUnOkupa33rucQ31fDjRj5gqhCoM2kx6Kl+SjivV7HR9XxVAwC4wjwOdMLIX6reUEC65XpUzy6q1Din1rThtzldg5F8mwm2U2emqe+gP1Xnz3BEWbCn6HH0ZCo/abWsotgQydT0twyJi6IP3gOMCGcHYH6rayXsu8giDwsrCWBcZ2nVKYPJoLvCa6/Bydzg8DW3ltIcJA4Q+IJ0wdwMdhjcpAI="
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  draft: true
  on:
    tags: true
